#!/bin/bash
## tdotool and xclip us need
## INSTALLATION ##
# See README.md for details  
# The default text editor is set to Scrivener. Edit Preferences below if you use a different program.

## PREFERENCES ##
CAYW_URL="http://localhost:23119/better-bibtex/cayw?format=pandoc" # Edit the URL as needed for a different citation marker format.

textEditor="Obsidian|Zettlr" # Replace "Scrivener" with the name of your preferred text editor (as it appears in the program window)
#widTE=$(xdotool search --onlyvisible $textEditor 2>/dev/null | head -1)
widTE=$(xdotool getactivewindow|head -1)
if ! [ $widTE ]; then
		notify-send "Please open $textEditor and try again, or edit the Zotpicknix script file to specify a different text editor."
		exit 3;
fi

BBT_status=$(/usr/bin/curl 'http://localhost:23119/better-bibtex/cayw?probe=probe' 2>/dev/null)

if [ "$BBT_status" == "ready" ] 2>/dev/null; then
		notify-send "Accessing Zotero picker..."
		old_copy=`xsel --output --clipboard`
		zte_old=$(xdotool search --onlyvisible "zotero")
		#xdotool windowactivate $zte --delay 100
		{
			for i in {1..100};
			do
				zte=$(xdotool search --onlyvisible "zotero"|sort|tail -1)
				if [[ ! "${old[@]}" =~ $zte ]] ; then
					xdotool windowactivate $zte
					break
				else
					sleep 0.3s
				fi

			done
		}&
		citation=$(/usr/bin/curl $CAYW_URL 2>/dev/null)
		echo "$citation" | xsel --input --clipboard  
		xdotool windowactivate $widTE && xdotool key ctrl+v space --window $widTE --delay 40  # Long delay minimises xdotool errors
		echo "$old_copy" | xsel --input --clipboard  
		#xdotool windowactivate $widTE && xdotool type --window $widTE --delay 40 "$citation" # Long delay minimises xdotool errors
		exit 0;

elif [ -z "$BBT_status" ]; then
		notify-send "Please launch Zotero with the Better BibTeX plugin. If Zotero is running, check 'Enable export by HTTP' in BBT and restart Zotero."
		xdotool windowactivate $widTE
		exit 4;

elif [ "$BBT_status" == "No endpoint found" ] 2>/dev/null; then
		notify-send "Better BibTeX cannot find your library. Ensure only one Zotero instance is open. If so, reinstall Better BibTeX."
else
		notify-send "Unknown error in Better BibTex. Please restart Zotero and try again."
fi
xdotool windowactivate $widTE
exit 5;

